import type { Post } from "./post-types";
import type { AnalyticsState } from "./analytics";
import type { PresenceState } from "./presence-types";
import type { SiteContent } from "./site-content-types";

export const DEFAULT_SITE_CONTENT: SiteContent = {
  site: {
    title: "qwq.my",
    description: "A soft hand-drawn personal blog built with Next.js.",
    faviconUrl: "",
    brandName: "qwq.my",
    heroTitle: "Ahoy~!!\nI'm snowball~!!",
    heroSubtitle: "Frontend engineer & interface tinkerer",
    heroTagline: "Problem solver :)",
    heroImageUrl: "",
    heroImageAlt: "Pastel hand-drawn mascot holding a small star wand",
    projectsIntro: "Small UI experiments, notes, and tools that keep the page alive.",
    githubUrl: "https://github.com/SnowballXueQiu",
    xUrl: "https://twitter.com/SnowballLoveYou",
    email: "i@qwq.my",
    showGithub: true,
    showX: true,
    showEmail: true,
  },
  me: [
    {
      id: "intro",
      kind: "intro",
      title: "SnowballXueQiu",
      summary: "Student, builder, Minecraft server engineer, and frontend developer.",
      enabled: true,
      imageUrl: "https://s2.loli.net/2024/07/14/KSNQxu9RBlWdbJ6.gif",
      imageAlt: "QwQ",
      items: [
        {
          title: "Self-introduction",
          subtitle: "Hello! I am SnowballXueQiu, a student at a public high school with a passion for computer technology.",
          meta: "About",
          url: "",
          color: "violet",
        },
      ],
      links: [],
    },
    {
      id: "teams",
      kind: "links",
      title: "Teams and contributions",
      summary: "Open-source, Minecraft server, and Linux community work.",
      enabled: true,
      items: [
        {
          title: "Vastsea",
          subtitle: "My Minecraft transit construction server, aiming to go beyond just a gaming experience.",
          meta: "Leadership",
          url: "https://github.com/TeamVastsea",
          color: "mint",
        },
        {
          title: "Flora Core",
          subtitle: "An open-source core plugin for Minecraft/Bukkit servers.",
          meta: "Contribution",
          url: "https://github.com/FloraCore",
          color: "pink",
        },
        {
          title: "LingmoOS",
          subtitle: "A Debian GNU/Linux-based operating system focused on system beautification.",
          meta: "Contribution",
          url: "https://github.com/LingmoOS",
          color: "blue",
        },
      ],
      links: [],
    },
    {
      id: "positions",
      kind: "timeline",
      title: "Positions",
      summary: "Current and past community roles.",
      enabled: true,
      items: [
        { title: "Co-founder, Technical Lead, and Operations", subtitle: "Vastsea", meta: "Current", url: "https://www.vastsea.cc/", color: "mint", past: false },
        { title: "Moderator of the JE and server plugins section", subtitle: "KLPBBS", meta: "Current", url: "https://klpbbs.com/space-uid-1082463.html", color: "blue", past: false },
        { title: "Frontend Developer", subtitle: "LingmoOS", meta: "Current", url: "https://lingmo.org", color: "violet", past: false },
        { title: "Moderator", subtitle: "Oxygen Community", meta: "Past", url: "https://bbs.oxygenstudio.cn/members/snowball_233.11/", color: "pink", past: true },
      ],
      links: [],
    },
    {
      id: "tech-stack",
      kind: "skills",
      title: "Tech stack",
      summary: "Minecraft Server Development ***, Rust ~~~, TypeScript ~~~, React ~~~, Docker ~~~, Go ~~~, Python ~~~.",
      enabled: true,
      items: [
        { title: "Minecraft Server Development", subtitle: "***", meta: "Expert", url: "", color: "pink" },
        { title: "TypeScript", subtitle: "~~~", meta: "Competent", url: "", color: "blue" },
        { title: "React", subtitle: "~~~", meta: "Competent", url: "", color: "violet" },
        { title: "Docker", subtitle: "~~~", meta: "Competent", url: "", color: "mint" },
      ],
      links: [
        {
          label: "WakaTime",
          value: "Coding activity",
          url: "https://wakatime.com/@ea22cbac-f1f5-4e51-a8ba-aa812b46f257",
          enabled: true,
        },
      ],
    },
    {
      id: "contacts",
      kind: "links",
      title: "Contact me",
      summary: "Places where you can find me.",
      enabled: true,
      items: [],
      links: [
        { label: "GitHub", value: "SnowballXueQiu", url: "https://github.com/SnowballXueQiu", enabled: true },
        { label: "Telegram", value: "Snowball_233", url: "https://t.me/Snowball_233", enabled: true },
        { label: "X", value: "SnowballLoveYou", url: "https://twitter.com/SnowballLoveYou", enabled: true },
        { label: "Email", value: "i@qwq.my", url: "mailto:i@qwq.my", enabled: true },
        { label: "Discord", value: "SnowballXueQiu", url: "", enabled: true },
      ],
    },
  ],
  projects: [
    {
      title: "Presence Board",
      summary: "A local macOS probe, API route, and live website widget for current app, editor file, device, and status.",
      status: "Live",
      tags: ["nextjs", "swiftui", "presence"],
      color: "mint",
      githubUrl: "",
    },
    {
      title: "Writing Garden",
      summary: "Searchable blog cards with topic filters, dynamic article pages, and a MongoDB-backed blog backend.",
      status: "Polishing",
      tags: ["blogs", "markdown", "admin"],
      color: "violet",
      githubUrl: "",
    },
  ],
  friends: [
    {
      name: "Mika Notes",
      url: "https://example.com",
      description: "Tiny essays about tools, study systems, and internet gardens.",
    },
  ],
  about: {
    copyright: "© 2026 snowball. Site content, writing, and visual direction are reserved unless otherwise noted.",
  },
};

const MARKDOWN_STYLE_PREVIEW = [
  "# Markdown Style Preview",
  "",
  "This article covers the supported writing blocks used by the renderer.",
  "",
  "::: toc Contents",
  ":::",
  "",
  "## Inline Markdown",
  "",
  "**Bold text**, __strong text__, ++underlined text++, _italic text_, [a normal link](https://qwq.my), `inline $x^2$ math`, and inline math $a^2 + b^2 = c^2$.",
  "",
  "---",
  "",
  "~~~",
  "",
  "===",
  "",
  "## KaTeX",
  "",
  "$$",
  "\\int_0^1 x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "$$",
  "\\begin{aligned}",
  "f(x) &= x^2 + 2x + 1\\\\",
  "     &= (x+1)^2",
  "\\end{aligned}",
  "$$",
  "",
  "$$",
  "\\sum_{n=1}^{5} n = 1 + 2 + 3 + 4 + 5 = 15",
  "$$",
  "",
  "## Mermaid",
  "",
  "```mermaid",
  "graph TD",
  "  A[Draft] --> B[Preview]",
  "  B --> C[Publish]",
  "```",
  "",
  "## Gallery",
  "",
  "::: gallery",
  "https://loremflickr.com/640/480/city?1",
  "https://loremflickr.com/640/480/city?2",
  "https://loremflickr.com/640/480/city?3",
  "![](https://loremflickr.com/640/480/city?4 'Image')",
  ":::",
  "",
  "## Grid",
  "",
  "::: grid {cols=3,gap=4}",
  "Grid 1",
  "Grid 2",
  "Grid 3",
  "https://loremflickr.com/640/480/city?1",
  "https://loremflickr.com/640/480/city?2",
  "https://loremflickr.com/640/480/city?3",
  "![](https://loremflickr.com/640/480/city?4 'Image')",
  "![](https://loremflickr.com/640/480/city?4 'Image')",
  "![](https://loremflickr.com/640/480/city?4 'Image')",
  ":::",
  "",
  "Media library images can be referenced as `![](/media/image-name.png)` after upload.",
  "",
  "## Warning And Banner",
  "",
  "::: warning",
  "_here be dragons_",
  ":::",
  "",
  "::: banner {error}",
  "_here be dragons_",
  ":::",
  "",
  "## Table",
  "",
  "| Feature | Syntax | Status |",
  "| --- | --- | --- |",
  "| KaTeX | `$x^2$` | supported |",
  "| Inline math | `$\\alpha + \\beta$` | supported |",
  "| Inline code math | `inline $x^2$ math` | supported |",
  "| Mermaid | code fence | supported |",
  "| Gallery | directive | supported |",
  "",
  "| Feature | Syntax | Status |",
  "| --- | --- | --- |",
  "| Spoiler | `||hidden text||` | supported |",
  "| Divider | `---` / `~~~` / `===` | supported |",
  "| TOC | `::: toc Contents` | supported |",
  "",
  "## Excalidraw",
  "",
  "```excalidraw",
  "{\"type\":\"excalidraw/clipboard\",\"elements\":[{\"type\":\"rectangle\",\"version\":14,\"versionNonce\":1361369853,\"isDeleted\":false,\"id\":\"_PSpf6pLwkWIJubC_tf9D\",\"fillStyle\":\"solid\",\"strokeWidth\":2,\"strokeStyle\":\"solid\",\"roughness\":1,\"opacity\":100,\"angle\":0,\"x\":545.0390625,\"y\":387.296875,\"strokeColor\":\"#1e1e1e\",\"backgroundColor\":\"transparent\",\"width\":177.53515625,\"height\":138.328125,\"seed\":1495751197,\"groupIds\":[],\"frameId\":null,\"roundness\":{\"type\":3},\"boundElements\":[],\"updated\":1706954302946,\"link\":null,\"locked\":false}],\"files\":{}}",
  "```",
  "",
  "## Collapse And Spoiler",
  "",
  "::: collapse Details",
  "Hidden notes can contain **Markdown**.",
  ":::",
  "",
  "This block is hidden until opened. Inline spoiler looks like ||hidden text||.",
  "",
  "## List",
  "",
  "- Unordered item",
  "- Another item with `inline $y^2$ math`",
  "1. Ordered item",
  "2. Ordered item with __strong__ text",
  "",
  "## Quote",
  "",
  "> This is a blockquote with **bold** and `inline $z^2$ math`.",
  "",
  "## One More Divider",
  "",
  "---",
  "",
  "## Final Note",
  "",
  "This preview now shows headings, paragraphs, lists, quotes, block math, inline math, inline code math, divider styles, TOC, gallery, grid, table, spoiler, collapse, mermaid, and excalidraw in one place.",
  "",
  "## Rich Link",
  "",
  "richlink https://github.com/Innei/Shiro",
  "",
  "[Innei/Shiro#129](https://github.com/Innei/Shiro/pull/129)",
  "",
  "https://github.com/Innei/Shiro/commit/6957e011439eb2d3cbf42bfb67ed81b07d4bcc2a",
].join("\n");

export const DEFAULT_POSTS: Post[] = [
  {
    slug: "markdown-style-preview",
    title: "Markdown Style Preview",
    summary: "A complete preview article for every supported Markdown extension.",
    date: "June 4, 2026",
    topic: "frontend",
    tags: ["markdown", "preview", "katex", "mermaid"],
    read: 2,
    color: "blue",
    views: 0,
    likes: 0,
    content: MARKDOWN_STYLE_PREVIEW,
  },
  {
    slug: "markdown-garden",
    title: "Markdown Garden",
    summary: "A tiny notebook for ideas, components, and sketchy experiments.",
    date: "May 28, 2026",
    topic: "design",
    tags: ["demo", "markdown", "styling"],
    read: 1,
    color: "violet",
    views: 0,
    likes: 0,
    content: "## A small garden\n\nThis garden is where small interface thoughts get planted before they become full projects.\n\nThe useful part is not the markdown itself. It is the rhythm around it: quick notes, durable tags, and a layout that makes old ideas easy to rediscover.\n\n$$\n\\text{idea} \\rightarrow \\text{note} \\rightarrow \\text{project}\n$$",
  },
  {
    slug: "soft-ui-field-notes",
    title: "Soft UI Field Notes",
    summary: "How rounded panels, pencil lines, and warm spacing keep pages friendly.",
    date: "May 22, 2026",
    topic: "frontend",
    tags: ["css", "layout", "tokens"],
    read: 2,
    color: "pink",
    views: 0,
    likes: 0,
    content: "## Structure first\n\nA soft interface still needs structure. The trick is to keep the grid disciplined while letting borders, shadows, and spacing feel handmade.\n\n- paper\n- ink\n- muted text\n- accent families\n\nThe best detail here is restraint.",
  },
  {
    slug: "presence-notes",
    title: "Presence Notes",
    summary: "Making little status widgets feel alive without making them noisy.",
    date: "May 19, 2026",
    topic: "systems",
    tags: ["presence", "state", "ui"],
    read: 1,
    color: "blue",
    views: 0,
    likes: 0,
    content: "Presence UI is most useful when it gives a page a pulse without demanding attention.\n\nA changing bpm number, currently editing label, and viewer count are enough to imply activity.",
  },
];

export const DEFAULT_ANALYTICS: AnalyticsState = {
  totalPageViews: 0,
  pages: {},
  updatedAt: new Date(0).toISOString(),
};

export const DEFAULT_PRESENCE: PresenceState = {
  status: "offline",
  location: "Shanghai",
  bpm: 72,
  device: {
    name: "Mac",
    os: "macOS",
  },
  activeApp: {
    name: "Unknown",
  },
  editing: {
    isEditor: true,
    editor: "Next.js",
    file: "app/page.tsx",
    branch: "main",
  },
  updatedAt: new Date(0).toISOString(),
  stale: true,
};
